// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBk7HP7zUrqFsP6FCLKcvuD0W3bxaxQs',
    appId: '1:96312158002:web:f8799faf6ec078f487592b',
    messagingSenderId: '96312158002',
    projectId: 'emanshopingcenter-70832',
    authDomain: 'emanshopingcenter-70832.firebaseapp.com',
    storageBucket: 'emanshopingcenter-70832.appspot.com',
    measurementId: 'G-DHLQEMX4FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1D_unYxpYAptuzjwz1x0B2pyrU4LPiF4',
    appId: '1:96312158002:android:540672ba25037ffe87592b',
    messagingSenderId: '96312158002',
    projectId: 'emanshopingcenter-70832',
    storageBucket: 'emanshopingcenter-70832.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWNlUgHkqKnWk8tpLXSm6Hfw7Ap9KU3bo',
    appId: '1:96312158002:ios:c7156937d9dd687587592b',
    messagingSenderId: '96312158002',
    projectId: 'emanshopingcenter-70832',
    storageBucket: 'emanshopingcenter-70832.appspot.com',
    iosBundleId: 'com.example.emanShopingCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWNlUgHkqKnWk8tpLXSm6Hfw7Ap9KU3bo',
    appId: '1:96312158002:ios:c7156937d9dd687587592b',
    messagingSenderId: '96312158002',
    projectId: 'emanshopingcenter-70832',
    storageBucket: 'emanshopingcenter-70832.appspot.com',
    iosBundleId: 'com.example.emanShopingCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeBk7HP7zUrqFsP6FCLKcvuD0W3bxaxQs',
    appId: '1:96312158002:web:7ea7d8d65034967687592b',
    messagingSenderId: '96312158002',
    projectId: 'emanshopingcenter-70832',
    authDomain: 'emanshopingcenter-70832.firebaseapp.com',
    storageBucket: 'emanshopingcenter-70832.appspot.com',
    measurementId: 'G-T361LGSX1J',
  );
}
